apiVersion: v1
kind: Deployment
metadata:
  name: audit
  labels: 
    app: audit
spec:
  selector:
    matchLabels:
      app: audit
  template:
    metadata:
      labels:
        app: audit
    spec:
      containers:
      - name: audit
        image: gcr.io/beholder-251311/audit
        imagePullPolicy: Always
        ports:
        - containerPort: 8081