
    core:
      image: localhost:5000/core
      ports:
      - target: 8083
        published: 8083
        protocol: tcp
      depends_on:
      - mongoaudit
      - activemq
      - search
      - user
    audit:
      image: localhost:5000/audit
      ports:
      - target: 8081
        published: 8081
        protocol: tcp
      depends_on:
        - mongoaudit
        - activemq
        - search
        - user
        - core
    react:
      image: localhost:5000/react
      ports:
      - target: 3000
        published: 3000
        protocol: tcp
      depends_on:
      - activemq
      - search
      - user
      - core
      - audit
    nginx:
      image: localhost:5000/nginx
      volumes:
      - type: bind
        source: ./nginx/nginx.conf
        target: /etc/nginx/nginx.conf
      ports:
      - target: 80
        published: 80
        protocol: tcp
      depends_on:
        - activemq
        - search
        - user
        - core
        - audit
        - react

