apiVersion: beholder/v1
kind: Deployment
metadata:
  name: react
  labels: 
    app: react
spec:
  selector:
    matchLabels:
      app: react
  template:
    metadata:
      labels:
        app: react
    spec:
      containers:
      - name: react
        image: lushilling/react:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000