apiVersion: beholder/v1
kind: Pod
metadata:
  name: activemq
  labels: 
    app: activemq
spec:
  securityContext:
    fsGroup: 1000
  containers:
    - name: activemq
      image: gcr.io/beholder-251311/activemq
      ports:
      - containerPort: 61616