apiVersion: beholder/v1
kind: Deployment
metadata:
  name: user
  labels: 
    app: user
spec:
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
      - name: user
        image: gcr.io/beholder-251311/user
        imagePullPolicy: Always
        ports:
        - containerPort: 5001